FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY apps/web/package*.json ./
RUN npm install

# Copy source code
COPY apps/web .

# Build application
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
