FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY apps/worker/package*.json ./
RUN npm install

# Copy source code
COPY apps/worker .

# Build application
RUN npm run build

CMD ["npm", "start"]
