FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY apps/api/package*.json ./
RUN npm install

# Copy source code
COPY apps/api .

# Build application
RUN npm run build

EXPOSE 8080

CMD ["npm", "start"]
